### ISSUE TITLE
Is the Comfortaa font curently used?

### ISSUE THREAD

**Issue by sorenstoutner** [feather-wallet/feather-docs#12]
The Comfortaa font is included in static/fonts.  It is referenced in:

https://github.com/feather-wallet/feather-docs/blob/d2268d431b4cce945d993898b4e209759a21d7a6/_includes/head.html#L2

But it doesn't appear to be currently used anywhere in the documentation (assuming I have reviewed the documentation correctly).

Was it a font that was used in the past but no longer?

**Comment by tobtoht** [comment]
Not sure what this was used for, I think this line can be removed.

**Comment by sorenstoutner** [comment]
Would you like me to prepare a PR?

**Comment by tobtoht** [comment]
Done in 52979224e917aee944756fb318b4d9eae1ae1d3a

**Comment by sorenstoutner** [comment]
You can also remove the following license as it no longer applies to any files.

https://github.com/feather-wallet/feather-docs/blob/master/static/fonts/LICENSE-comforta.txt

**Comment by tobtoht** [comment]
Thanks, done in https://github.com/feather-wallet/feather-docs/commit/2c9c01ab4e1add60ce17648fe20b96db79a5d37c
